---
- name: restart munge
  service:
    name: munge
    state: restarted

- name: reload slurmd
  service:
    name: "{{ slurmd_service_name }}"
    state: reloaded
  when: "slurm_start_services and ('slurmexechosts' in group_names or 'exec' in slurm_roles)"

- name: restart slurmd
  service:
    name: "{{ slurmd_service_name }}"
    state: restarted
  when: "slurm_start_services and ('slurmexechosts' in group_names or 'exec' in slurm_roles)"

- name: reload slurmctld
  service:
    name: "{{ slurmctld_service_name }}"
    state: reloaded
  when: "slurm_start_services and ('slurmservers' in group_names or 'controller' in slurm_roles)"

- name: restart slurmctld
  service:
    name: "{{ slurmctld_service_name }}"
    state: restarted
  when: "slurm_start_services and ('slurmservers' in group_names or 'controller' in slurm_roles)"

- name: reload slurmdbd
  service:
    name: "{{ slurmdbd_service_name }}"
    state: reloaded
  when: "slurm_start_services and ('slurmdbdservers' in group_names or 'dbd' in slurm_roles)"
